name: PR Merge
on:
  pull_request_target:
    types:
      - auto_merge_enabled
jobs:
  pr-automerge:
    runs-on: ubuntu-latest
    steps:
    - uses: davideviolante/pr-automerge-action@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        merge-method: 'merge' 
        min-approvals: 1
        base-ref: 'main'
